version: "3"

services:
  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ./docker/wait-for-it.sh pg:5432 -- npm run start:prod
    depends_on:
      - "pg"
    ports:
      - 7001:7001

  pg:
    image: postgres:11
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
