version: "3"

services:
  server:
    command: ./docker/wait-for-it.sh pg:5432 -- npm run start:dev
    volumes:
      - "../:/usr/src/app"

  adminer:
    image: adminer
    ports:
      - 7002:8080
